sudo: required
services:
  - docker

before_install:
  - docker build -t rksingh0100/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rksingh0100/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-486713076911"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET